services:
  nginx:
    image: nginx:1.27-alpine
    depends_on: [php, mysql]
    ports:
      - "80:80"
    volumes:
      - ../../../backend:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app_network

  php:
    build:
      context: ../../../backend
      dockerfile: Dockerfile.build
    volumes:
      - ../../../backend:/var/www
    networks:
      - app_network

  frontend:
    build:
      context: ../../../frontend
      dockerfile: Dockerfile.build
    ports:
      - "5173:80"
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: sistema_clinicas
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    networks:
      - app_network

networks:
  app_network:

volumes:
  dbdata:
